xenit-eu/alfred-api

.github/pull_request_template.md
Jenkinsfile
README.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-346

Alfredapi-346

---

CHANGELOG.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-

ALFREDAPI-346: Release v2.2.0

---

Jenkinsfile
apix-impl/build.gradle
apix-interface/build.gradle
apix-interface/src/main/java/eu/xenit/apix/search/FacetSearchResult.java
publish.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-346

ALFREDAPI-346: Publish sources, javadoc apix-interface

---

developer-documentation/developer.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-346

ALFREDAPI-346: Fix dev guide publish link

---

CHANGELOG.md
apix-docker/50/build.gradle
apix-docker/50/docker-compose.yml
apix-docker/51/build.gradle
apix-docker/51/docker-compose.yml
apix-docker/52/build.gradle
apix-docker/52/docker-compose.yml
apix-docker/60/build.gradle
apix-docker/60/docker-compose.yml
apix-docker/61/build.gradle
apix-docker/61/docker-compose.yml

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-

Alfredapi 385 Change integration test docker images to use harbor

---

CHANGELOG.md
README.md
apix-docker/build.gradle
apix-impl/build.gradle
apix-impl/src/integration-test/java/eu/xenit/apix/tests/ApixImplBundleFilter.java
apix-impl/src/integration-test/java/eu/xenit/apix/tests/search/SearchNodeParsingTest.java
apix-impl/src/integration-test/java/eu/xenit/apix/tests/search/SearchServiceTest.java
apix-integrationtests-model-amp/build.gradle
apix-integrationtests-model-amp/src/main/amp/module.properties
apix-integrationtests/build.gradle
apix-rest-v1/src/main/java/eu/xenit/apix/rest/v0/dictionary/DictionaryServiceChecksumWebscript.java
apix-rest-v1/src/main/java/eu/xenit/apix/rest/v0/metadata/MetadataBulkWebscript.java
apix-rest-v1/src/main/java/eu/xenit/apix/rest/v0/metadata/MetadataGetWebscript.java
apix-rest-v1/src/main/java/eu/xenit/apix/rest/v0/metadata/MetadataPostWebscript.java
build.gradle
javadoc/build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-368

ALFREDAPI-368: Replace dying gradle plugins

---

CHANGELOG.md
apix-impl/src/integration-test/java/eu/xenit/apix/tests/search/SearchServiceTest.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchService.java
apix-impl/src/test/java/eu/xenit/apix/tests/search/SearchServiceUnitTest.java
apix-interface/src/main/java/eu/xenit/apix/search/SearchQuery.java
apix-interface/src/main/java/eu/xenit/apix/search/SearchQueryConsistency.java
apix-interface/src/main/java/eu/xenit/apix/search/SearchQueryResult.java
apix-interface/src/main/java/eu/xenit/apix/search/nodes/PropertySearchNode.java
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-

Alfredapi 377

---

CHANGELOG.md
build.gradle
developer-documentation/examples/build.gradle

See:
- https://support.sonatype.com/hc/en-us/articles/360041287334
- https://jfrog.com/blog/secure-jcenter-with-https/
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-404

Connect to artifact repositories using HTTPS

---

CHANGELOG.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-409

ALFREDAPI-409: Release 2.3.0

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-409

ALFREDAPI-409: Post-release bump

---

CHANGELOG.md
apix-docker/61/build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-457

Alfredops 457 Updated War image for Alfresco 6.1

---

CHANGELOG.md
apix-interface/src/main/java/eu/xenit/apix/categories/Category.java
apix-interface/src/main/java/eu/xenit/apix/content/IContentService.java
apix-interface/src/main/java/eu/xenit/apix/node/INodeService.java
apix-interface/src/main/java/eu/xenit/apix/permissions/IPermissionService.java
apix-interface/src/main/java/eu/xenit/apix/search/SearchQueryResult.java
apix-interface/src/main/java/eu/xenit/apix/versionhistory/IVersionHistoryService.java

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-407

ALFREAPI-407 Updated documentation

---

CHANGELOG.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-415

ALFREDAPI-415: Release 2.4.0

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-415

ALFREDAPI-415: Post release commit

---

CHANGELOG.md
apix-docker/build.gradle
apix-impl/50/overrides.gradle
apix-impl/51/overrides.gradle
apix-impl/52/overrides.gradle
apix-impl/60/overrides.gradle
apix-impl/61/overrides.gradle
apix-impl/build.gradle
apix-impl/src/integration-test/java/eu/xenit/apix/tests/search/SearchServiceTest.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchService.java

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-422

Alfredapi 422 fix totalItemsReturned for TDMQ's

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-432

ALFREDAPI-432 release v2.5.0

---

apix-docker/50/build.gradle
apix-docker/50/debug-extension.docker-compose.yml
apix-docker/51/build.gradle
apix-docker/51/debug-extension.docker-compose.yml
apix-docker/52/build.gradle
apix-docker/60/build.gradle
apix-docker/60/debug-extension.docker-compose.yml
apix-docker/61/build.gradle
apix-docker/61/debug-extension.docker-compose.yml
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-424
No changelog update since this is purely for the development phase. This should not impact production artifacts

ALFREDAPI-424 add sharecontainers and c4a amps

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-440

ALFREDAPI-440 Release v2.5.1

---

CHANGELOG.md
apix-docker/50/build.gradle
apix-docker/50/debug-extension.docker-compose.yml
apix-docker/51/build.gradle
apix-docker/51/debug-extension.docker-compose.yml
apix-docker/52/build.gradle
apix-docker/60/build.gradle
apix-docker/60/debug-extension.docker-compose.yml
apix-docker/61/build.gradle
apix-docker/61/debug-extension.docker-compose.yml
apix-impl/src/integration-test/java/eu/xenit/apix/tests/search/SearchServiceTest.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/metadata/NodeService.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchFacetsServiceImpl.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchService.java
apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsBaseUnitTest.java
apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsFromInaccessibleNodeUnitTest.java
apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsFromNodeUnitTest.java
apix-impl/src/test/java/eu/xenit/apix/tests/search/SearchFacetServiceUnitTest.java
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-440

Release v2.5.1

---

CHANGELOG.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-443

ALFREDAPI-443 Release v2.5.2

---

CHANGELOG.md
apix-docker/50/build.gradle
apix-docker/50/debug-extension.docker-compose.yml
apix-docker/51/build.gradle
apix-docker/51/debug-extension.docker-compose.yml
apix-docker/52/build.gradle
apix-docker/60/build.gradle
apix-docker/60/debug-extension.docker-compose.yml
apix-docker/61/build.gradle
apix-docker/61/debug-extension.docker-compose.yml
apix-impl/src/integration-test/java/eu/xenit/apix/tests/search/SearchServiceTest.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/metadata/NodeService.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchFacetsServiceImpl.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchService.java
apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsBaseUnitTest.java
apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsFromInaccessibleNodeUnitTest.java
apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsFromNodeUnitTest.java
apix-impl/src/test/java/eu/xenit/apix/tests/search/SearchFacetServiceUnitTest.java
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-443

ALFREDAPI-443 Fix difference between master and release-2.x

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-443

ALFREDAPI-443 Release 2.5.2 - post release commit

---

CHANGELOG.md
apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/PeopleTest.java
apix-impl/src/integration-test/java/eu/xenit/apix/tests/people/PeopleServiceTest.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/people/PeopleService.java
apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/people/PeopleWebscript1.java
apix-rest-v1/src/main/java/eu/xenit/apix/rest/v2/people/PeopleWebscript.java

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-428

ALFREDAPI-428 Change getPerson to getPersonOrNull in PeopleService

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-448

ALFREDAPI-448 Release v2.6.0

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-448

ALFREDAPI-448 version bump to v2.6.1

---

CHANGELOG.md
apix-impl/src/integration-test/java/eu/xenit/apix/tests/properties/PropertyServiceTest.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/dictionary/AspectService.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/dictionary/DictionaryService.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/dictionary/PropertyService.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/properties/PropertyServiceImpl.java
apix-interface/src/main/java/eu/xenit/apix/dictionary/aspects/Aspects.java
apix-interface/src/main/java/eu/xenit/apix/dictionary/aspects/IAspectService.java
apix-interface/src/main/java/eu/xenit/apix/dictionary/properties/IPropertyService.java
apix-interface/src/main/java/eu/xenit/apix/properties/IPropertyService.java
apix-interface/src/main/java/eu/xenit/apix/properties/Properties.java
apix-interface/src/main/java/eu/xenit/apix/properties/PropertyDefinition.java
apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/dictionary/DictionaryWebScript1.java

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-442

ALFREDAPI-442 implement webscript for /properties and /aspects

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-452

ALFREDAPI-452: Post-release bump

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-453

ALFREDAPI-453 Release v2.7.0

---

CHANGELOG.md

ALFREDAPI-453 Remove added Comments API entry in changelog for v2.6.1

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-461

ALFREDAPI-461 reintroduce xenit maven repo

---

CHANGELOG.md
Jenkinsfile
apix-impl/build.gradle
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-453

ALFREDAPI-453: Make publish explicit in Jenkinsfile

---

CHANGELOG.md

ALFREDAPI-453 Update changelog for release date

---

CHANGELOG.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-453 

ALFREDAPI-453: Correct 418->453 in CHANGELOG

---

CHANGELOG.md
apix-impl/52/src/main/java/eu/xenit/apix/alfresco52/SearchServiceImpl52.java
apix-impl/60/src/main/java/eu/xenit/apix/alfresco60/SearchServiceImpl60.java
apix-impl/61/src/main/java/eu/xenit/apix/alfresco61/SearchServiceImpl61.java
apix-impl/62/src/main/java/eu/xenit/apix/alfresco62/SearchServiceImpl62.java
apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchService.java
apix-impl/src/test/java/eu/xenit/apix/tests/search/SearchServiceUnitTest.java
apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/temp/V1SearchWebscriptTest.java

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-470

ALFREDAPI-470: Search limit & memory problems

---

CHANGELOG.md
apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/CopyNodeTest.java
apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/CreateNodeTest.java
apix-interface/src/main/java/eu/xenit/apix/exceptions/FileExistsException.java
apix-rest-v1/src/main/java/eu/xenit/apix/rest/exceptions/FileExistsException.java
apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/internal/ApixArgumentResolver.java
apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/nodes/NodesWebscript1.java

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-445

ALFREDAPI-445 add exception handler for fileExistsException

---

CHANGELOG.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-474

ALFREDAPI-474 Release v2.7.1

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-474

ALFREDAPI-474 post-release version bump

---

CHANGELOG.md
README.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-481

Add Xenit blurb

---

CHANGELOG.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-487

ALFREDAPI-487: Release v3.0.0

---

build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-487
Forgot to set correct version number before release.

ALFREDAPI-487: Bump version to 3.0.0

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-<487>

Merge master into release for 3.0.0 (again)

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-487

ALFREDAPI-487: Post-release bump

---

CHANGELOG.md
apix-impl/src/main/java/eu/xenit/apix/alfresco/categories/CategoryService.java
apix-integrationtests/src/main/java/eu/xenit/apix/tests/categories/CategoryServiceTest.java
apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/categories/CategoryWebScript1.java

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-490

Alfredapi 490 swmcat

---

CHANGELOG.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-493

ALFREDAPI-493: Release 3.0.1

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-493

ALFREDAPI-493: Post release commit

---

CHANGELOG.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-496

ALFREDAPI-496: Release 3.0.2

---

CHANGELOG.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-510

ALFREDAPI-510: Update CHANGELOG

---

CHANGELOG.md
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-514

Alfredapi 514 fix snapshot qualifier

---

CHANGELOG.md
apix-impl/build.gradle
apix-interface/build.gradle
apix-rest-v1/build.gradle

ALFREDAPI-516 Cleanup classpath 

---

apix-docker/62/build.gradle
apix-impl/build.gradle
build.gradle

XENOPS-1081 fix bump version to 4.1.0

---

.github/workflows/ci.yml
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-522
Update legacy Cloudsmith link

ALFREDAPI-522 [Update] legacy CS link

---

.github/workflows/ci.yml
apix-integrationtests/src/main/java/eu/xenit/apix/tests/workflow/methods/WorkflowService_SearchContextMyPooledTasks_Test.java

Alfredapi 521 merge release

---

CHANGELOG.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-535

ALFREDAPI-535: Release 5.0.0

---

CHANGELOG.md
alfresco/70/overrides.gradle
alfresco/71/overrides.gradle
alfresco/72/overrides.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-353
Merge master into release (2nd)

Alfredapi 535: merge2

---

docs/README.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-541

ALFREDAPI-541: Update README for docs

---

CHANGELOG.md
apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchFacetsServiceImpl.java
apix-impl/src/test/java/eu/xenit/apix/tests/search/SearchFacetServiceUnitTest.java
build.gradle

ALFREDAPI-544 fix Date range search

---

CHANGELOG.md

ALFREDAPI-550 release 5.0.2

---

CHANGELOG.md
apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchFacetsServiceImpl.java
apix-impl/src/test/java/eu/xenit/apix/tests/search/SearchFacetServiceUnitTest.java
build.gradle

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-550

Release <- master

---

CHANGELOG.md
apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchFacetsServiceImpl.java
apix-impl/src/test/java/eu/xenit/apix/tests/search/SearchFacetServiceUnitTest.java
build.gradle
docs/README.md

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-544

Release-5.0.2

---

CHANGELOG.md
docs/user/user-guide.md

ALFREDAPI-560 [RELEASE] 6.0.0

---

.github/workflows/ci.yml
publish.gradle

ALFREDAPI-560 [Rollback] publish.signing

---

.github/workflows/ci.yml
publish.gradle

ALFREDAPI-560 [fix] signing alfred-api-interface

---

CHANGELOG.md

ALFREDAPI-560 [Update] Changelog

---

.github/workflows/ci.yml
CHANGELOG.md
docs/user/user-guide.md
publish.gradle

Release 6.0.0

---

.github/workflows/ci.yml
CHANGELOG.md
apix-integrationtests/alfresco/src/main/java/eu/xenit/apix/rest/v1/tests/NodeContentTest.java
apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/nodes/NodesWebscript1.java

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-563

Alfredapi 563

---

.github/workflows/ci.yml
CHANGELOG.md
alfred-api-docker/233/build.gradle
alfred-api-docker/233/debug-extension.docker-compose.yml
alfred-api-docker/233/docker-compose.yml
alfred-api-docker/234/build.gradle
alfred-api-docker/234/debug-extension.docker-compose.yml
alfred-api-docker/234/docker-compose.yml
alfred-api-impl/src/main/java/eu/xenit/alfred/api/alfresco/comments/CommentService.java
alfred-api-impl/src/main/java/eu/xenit/alfred/api/alfresco/search/SearchService.java
alfred-api-integrationtests-client/alfresco/src/main/java/eu/xenit/alfred/api/tests/metadata/NodeServiceTest.java
alfred-api-rest/build.gradle
alfresco/232/overrides.gradle
alfresco/233/overrides.gradle
alfresco/234/overrides.gradle
docs/user/user-guide.md
settings.gradle

ALFREDAPI-569  Make Alfred API compatible with Alfresco 23.3/23.4
