xenit-eu/alfred-api

CHANGELOG.md, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/workingcopies/WorkingcopiesWebscript1.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-387
Breaking changes include adding, changing or removing endpoints and/or JSON objects used in requests and responses. --> API change: added/changed 500 response to 404 response
=> Alfredapi 387

CHANGELOG.md, apix-docker/50/docker-compose.yml, apix-docker/51/docker-compose.yml, apix-docker/52/docker-compose.yml, apix-docker/60/docker-compose.yml, apix-docker/61/docker-compose.yml, build.gradle
The primary publishing account of our docker images  has changed from [/u/xeniteu](https://hub.docker.com/u/xeniteu) to [/u/xenit](https://hub.docker.com/u/xenit), and the former will likely be deleted soon. This PR updates the relevant images (only postgres) to the new publishing account, and implicitly uses `:latest`, which is recommended for integration tests' postgres.
=> ALFREDAPI-385 Use maintained images for postgres

apix-docker/60/docker-compose.yml
The docker-compose for the 6.0 was still using the old reference to the docker image for Solr.
=> Use correct docker image for Solr in 6.0 test

build.gradle
The Xenit private artifactory is listed as a repository in `buildscript{ }`.
Since all used plugins are open source and published to gradle plugin portal or other repositories, these private repositories can be removed.
=> Remove dependency on private artifactory for buildscript

CHANGELOG.md, apix-impl/src/main/java/eu/xenit/apix/alfresco/configuration/ConfigurationServiceImpl.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-410
- [ X] Is [CHANGELOG.md](https://github.com/xenit-eu/alfred-api/blob/master/CHANGELOG.md) extended?
- [ X] Does this PR avoid breaking the API? 
=> ALFREDAPI-410 wrap Data Dictionary lookup with runAsSystem

CHANGELOG.md, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/nodes/NodesWebscript1.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-419
- [ X ] Is [CHANGELOG.md](https://github.com/xenit-eu/alfred-api/blob/master/CHANGELOG.md) extended?
- [ X ] Does this PR avoid breaking the API? 
- [ X ] Does the PR comply to REST HTTP result codes policy outlined in the [developer guide](https://github.com/xenit-eu/alfred-api/blob/master/developer-documentation)?
- [ X ] Does the PR follow our [coding styleguide and other active procedures](https://xenitsupport.jira.com/wiki/spaces/XEN/pages/624558081/XeniT+Enhancement+Proposals+XEP)?
- [ X ] Is usage of `this.` prefix avoided?
=> Add html decoding to deleteAssociation endpoint

CHANGELOG.md, apix-impl/50/overrides.gradle, apix-impl/50/src/main/config/module.properties, apix-impl/51/overrides.gradle, apix-impl/51/src/main/config/module.properties, apix-impl/52/overrides.gradle, apix-impl/52/src/main/config/module.properties, apix-impl/60/overrides.gradle, apix-impl/60/src/main/config/module.properties, apix-impl/61/overrides.gradle, apix-impl/61/src/main/config/module.properties, apix-impl/build.gradle
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-416
=> ALFREDAPI-416 Removed max repository version from module.properties for builds for most recent Alfresco 

CHANGELOG.md, apix-impl/src/integration-test/java/eu/xenit/apix/tests/metadata/NodeServiceTest.java, apix-impl/src/main/java/eu/xenit/apix/alfresco/metadata/NodeService.java, apix-interface/src/main/java/eu/xenit/apix/node/INodeService.java, apix-interface/src/main/java/eu/xenit/apix/node/NodeAssociations.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/ApixV1Webscript.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/nodes/NodesWebscript1.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/sites/SitesWebscript1.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v2/ApixV2Webscript.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v2/nodes/NodesWebscriptV2.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-420
=> Extend NodeAssociations object to include peer-source associations

CHANGELOG.md, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/AllNodeInfoTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/AssociationsTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/BaseTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/BulkTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/CheckoutCheckinTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/CopyNodeTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/CreateNodeTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/MetadataTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/MoveNodeTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/NodeContentTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/PathTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/PermissionsTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/SetInheritParentPermissionsTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/VersionHistoryTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/temp/UploadFileTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v2/tests/AllNodeInfoTest.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/nodes/NodesWebscript1.java, build.gradle
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-421
> Pr adds explicit ApiResponse 403 to NodesWebscript endpoints
=> Alfredapi 421 Add 403 Not Authorized responses to NodesWebscript1

CHANGELOG.md, apix-impl/src/integration-test/java/eu/xenit/apix/tests/search/SearchServiceTest.java, apix-impl/src/main/java/eu/xenit/apix/alfresco/dictionary/PropertyTypeCheckService.java, apix-impl/src/main/java/eu/xenit/apix/alfresco/search/FtsNodeVisitor.java, apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchService.java, apix-impl/src/test/java/eu/xenit/apix/tests/search/FtsNodeVisitorTest.java, apix-interface/src/main/java/eu/xenit/apix/search/nodes/PropertySearchNode.java, apix-interface/src/test/java/eu/xenit/apix/search/nodes/PropertySearchNodeTest.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-427
Fixes #42 
=> Replace terms with property values that will cause Invalid Number Exceptions in Solr 6 with dummy terms in FtsNodeVisitor

CHANGELOG.md, apix-impl/src/main/java/eu/xenit/apix/alfresco/properties/PropertyServiceImpl.java, apix-impl/src/main/java/eu/xenit/apix/alfresco/translation/ResourceBundleTranslationKey.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-365
=> ALFREDAPI-365 decrease logging levels to avoid logspam

CHANGELOG.md, apix-docker/52/debug-extension.docker-compose.yml, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/AllNodeInfoTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v2/tests/AllNodeInfoTest.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/ApixV1Webscript.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/nodes/NodesWebscript1.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v2/ApixV2Webscript.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v2/nodes/NodesWebscriptV2.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-412
-> getAllNodeInfo may now return 400 responses instead of unwarranted 500 or faulty 200 responses.
=> ALFREDAPI-412 handle null and not authorized cases in getAllNodeInfo

CHANGELOG.md, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/BaseTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/temp/UploadFileTest.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/nodes/NodesWebscript1.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-388
=> Alfredapi 388: handle upload usecase with preexisting file

CHANGELOG.md, apix-impl/src/main/java/eu/xenit/apix/alfresco/metadata/NodeService.java, apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsBaseUnitTest.java, apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsFromInaccessibleNodeUnitTest.java, apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsFromNodeUnitTest.java
ALFREDAPI-438 Replace hasReadPermission with hasPermission to avoid an Alfresco bug that prevents usage of that method and throws AcessDeniedException
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-438
=> ALFREDAPI-438 Fix AcessDeniedException in getAncestors - change hasReadPermission to hasPermission 

CHANGELOG.md, apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchFacetsServiceImpl.java, apix-impl/src/test/java/eu/xenit/apix/tests/search/SearchFacetServiceUnitTest.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-439
=> Alfredapi 439 Fixed issue where category facet values would be displayed with their noderef instead of their name

CHANGELOG.md, apix-impl/src/integration-test/java/eu/xenit/apix/tests/search/SearchServiceTest.java, apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchService.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-437
~~I'm looking to improve the test performance a bit before getting this merged.~~
~~I'm opening the PR already for remarks beside test performance.~~
Fixing the `@Before` logic considering integration tests is out of scope
Integration tests introduced here are just going to be slow
=> Alfredapi 437 paged searches for transactional queries can not fetch more than 1000 results

CHANGELOG.md, apix-docker/50/build.gradle, apix-docker/50/debug-extension.docker-compose.yml, apix-docker/51/build.gradle, apix-docker/51/debug-extension.docker-compose.yml, apix-docker/52/build.gradle, apix-docker/60/build.gradle, apix-docker/60/debug-extension.docker-compose.yml, apix-docker/61/build.gradle, apix-docker/61/debug-extension.docker-compose.yml, apix-impl/src/integration-test/java/eu/xenit/apix/tests/search/SearchServiceTest.java, apix-impl/src/main/java/eu/xenit/apix/alfresco/metadata/NodeService.java, apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchFacetsServiceImpl.java, apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchService.java, apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsBaseUnitTest.java, apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsFromInaccessibleNodeUnitTest.java, apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsFromNodeUnitTest.java, apix-impl/src/test/java/eu/xenit/apix/tests/search/SearchFacetServiceUnitTest.java, build.gradle
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-440
=> Alfredapi 440 Release v2.5.1 (3nd attempt)

CHANGELOG.md, build.gradle
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-440
=> ALFREDAPI-440 Release 2.5.1 - post release commit

CHANGELOG.md, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/CopyNodeTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v2/tests/CopyNodeTest.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/nodes/CreateNodeOptions.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/nodes/NodesWebscript1.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v2/nodes/NodesWebscriptV2.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-338
=> ALFREDAPI-338 Changed CopyFrom behaviour to also set the provided properties

CHANGELOG.md, apix-impl/src/main/java/eu/xenit/apix/alfresco/permissions/PermissionService.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-395
=> ALFREDAPI-395 Change loglevels of PermissionService#hasPermission

CHANGELOG.md, apix-impl/50/src/main/java/eu/xenit/apix/alfresco50/CommentServiceImpl50.java, apix-impl/51/src/main/java/eu/xenit/apix/alfresco51/CommentServiceImpl51.java, apix-impl/52/src/main/java/eu/xenit/apix/alfresco52/CommentServiceImpl52.java, apix-impl/60/src/main/java/eu/xenit/apix/alfresco60/CommentServiceImpl60.java, apix-impl/61/src/main/java/eu/xenit/apix/alfresco61/CommentServiceImpl61.java, apix-impl/src/integration-test/java/eu/xenit/apix/rest/v1/tests/CommentsTest.java, apix-impl/src/integration-test/java/eu/xenit/apix/tests/comments/CommentServiceTest.java, apix-impl/src/main/java/eu/xenit/apix/alfresco/comments/CommentService.java, apix-interface/src/main/java/eu/xenit/apix/comments/Comment.java, apix-interface/src/main/java/eu/xenit/apix/comments/Conversation.java, apix-interface/src/main/java/eu/xenit/apix/comments/ICommentService.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/nodes/NodesWebscript1.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-298
This change adds a new interface to the java api and extends the rest api with 3 new endpoints
=> Alfredapi 298 - Add CRUD api for comments

CHANGELOG.md
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-448
=> ALFREDAPI-448 Removed entry from changelog

CHANGELOG.md, apix-impl/src/main/java/eu/xenit/apix/alfresco/metadata/NodeService.java, apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsBaseUnitTest.java, apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsFromInaccessibleNodeUnitTest.java, apix-impl/src/test/java/eu/xenit/apix/tests/metadata/AncestorsFromNodeUnitTest.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-438
=> ALFREDAPI-438 Corrected permission that is checked in ancestors webscript + related tests

CHANGELOG.md, apix-docker/61/debug-extension.docker-compose.yml, apix-docker/62/debug-extension.docker-compose.yml, apix-impl/src/main/java/eu/xenit/apix/alfresco/people/PeopleService.java, apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/PeopleTest.java, apix-integrationtests/src/main/java/eu/xenit/apix/rest/v2/tests/PeopleTest.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-466
=> Alfredapi 466 Enable usage of -me- to retrieve current user

CHANGELOG.md, apix-impl/src/main/java/eu/xenit/apix/alfresco/sites/SiteService.java
Fixes https://xenitsupport.jira.com/browse/NYCSANSUP-34
=> NYCSANSUP-34 Rerun site component retrieval upon accessdenied.

CHANGELOG.md, apix-impl/build.gradle, apix-integrationtests/build.gradle
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-473
=> ALFREDAPI-473: Integration tests are again run

CHANGELOG.md, apix-impl/src/main/java/eu/xenit/apix/alfresco/configuration/ConfigurationServiceImpl.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/configuration/ConfigurationWebscript1.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-184
=> ALFREDAPI-184 Improve graceful handling of bad input in ConfigurationWebscript1

apix-impl/src/main/java/eu/xenit/apix/alfresco/dictionary/AspectService.java, apix-impl/src/main/java/eu/xenit/apix/alfresco/dictionary/TypeService.java, apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/DictionaryTest.java, apix-interface/src/main/java/eu/xenit/apix/dictionary/aspects/AspectDefinition.java, apix-interface/src/main/java/eu/xenit/apix/dictionary/types/TypeDefinition.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-296
Pr will add a list of qnames for all aspects that are mandatory for the requested type or aspect definition.
=> Alfredapi 296

apix-integrationtests/src/main/java/eu/xenit/apix/rest/staging/tests/WorkflowTest.java, apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/AllNodeInfoTest.java, apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/BulkTest.java, apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/MetadataTest.java, apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/MoveNodeTest.java, apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/temp/UploadFileTest.java, apix-integrationtests/src/main/java/eu/xenit/apix/rest/v2/tests/AllNodeInfoTest.java, apix-integrationtests/src/main/java/eu/xenit/apix/tests/search/SearchServiceTest.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v2/groups/GroupsWebscript.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-ALFREDAPI-484
- [N/A] Does this PR avoid breaking the API? 
- [N/A] Does the PR comply to REST HTTP result codes policy outlined in the [user guide](https://docs.xenit.eu/alfred-api/stable-user/rest-api/index.html#rest-http-result-codes)?
- [N/A] Is error handling done through a method annotated with `@ExceptionHandler` in the webscript classes?
=> ALFREDAPI-484 adjust logging on tests from info to debug

CHANGELOG.md, apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchFacetsServiceImpl.java, apix-impl/src/test/java/eu/xenit/apix/tests/search/SearchFacetServiceUnitTest.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-378
=> ALFREDAPI-378 replace serviceregistry calls for facetlabeldisplayhandlerregistry and solrfacethelperserviceregistry

CHANGELOG.md, apix-docker/52/build.gradle, apix-docker/61/build.gradle, apix-docker/62/build.gradle, apix-docker/70/build.gradle, apix-docker/build.gradle
Fixes https://xenitsupport.jira.com/browse/XENOPS-891
Changes to 61 are temporary since the latest hotfix for this version has an issue (documented separately). I've pinned the war & docker image to the previous version.
- [N/A] Is error handling done through a method annotated with `@ExceptionHandler` in the webscript classes?
- [N/A] Is usage of `this.` prefix avoided?
=> XENOPS-891 update wars for 52, 62 & 70 to latest hotfix

CHANGELOG.md, apix-impl/src/main/java/eu/xenit/apix/alfresco/metadata/NodeService.java, apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/CopyNodeTest.java, apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/NodesBaseTest.java, apix-integrationtests/src/main/java/eu/xenit/apix/tests/metadata/NodeServiceTest.java, apix-interface/src/main/java/eu/xenit/apix/data/QName.java, apix-interface/src/main/java/eu/xenit/apix/node/INodeService.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/nodes/CreateNodeOptions.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/nodes/NodesWebscript1.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-492
=> Alfredapi 492

CHANGELOG.md, apix-integrationtests/build.gradle
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-497
=> ALFREDAPI-497: Re-enable composeDown after integrationTest

build.gradle
=> XENOPS-1081 fix snapshot naming and bump version to 4.1

.github/workflows/ci.yml
=> ALFREDAPI-518 fix publishing

.github/workflows/ci.yml
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-521
=> Alfredapi 521 ci

CHANGELOG.md, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/ApixV1Webscript.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/bulk/BulkWebscript1.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-520
=> Alfredapi 520 mvc branch fix

CHANGELOG.md, build.gradle
=> ALFREDAPI-521-Bump-version [Update] version 4.0.2

apix-integrationtests/alfresco/src/main/java/eu/xenit/apix/rest/v1/tests/ConfigurationTest.java, apix-rest-v1/src/main/java/eu/xenit/apix/rest/v1/configuration/ConfigurationWebscript1.java
=> ALFREDAPI-523 fix configuration endpoint

CHANGELOG.md, apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchFacetsServiceImpl.java, apix-impl/src/test/java/eu/xenit/apix/tests/search/SearchFacetServiceUnitTest.java
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-531
=> ALFREDAPI-531 fix facet qname splitting

CHANGELOG.md, README.md, apix-docker/70/docker-compose.yml, apix-docker/71/docker-compose.yml, apix-docker/72/docker-compose.yml, apix-docker/73/docker-compose.yml, apix-docker/74/docker-compose.yml
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-527
=> Alfredapi-527: ports

README.md
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-519
=> ALFREDAPI-519: Update Maven badge to alfred.api

CHANGELOG.md, apix-impl/build.gradle, build.gradle
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-538
=> ALFREDAPI-538 Fixed issue where errors related to jackson libraries would show up in the Alfresco logs while starting

CHANGELOG.md, apix-interface/build.gradle
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-540
=> Alfredapi 540/artifactnames

CHANGELOG.md, docs/swagger-ui/swagger.json, docs/user/user-guide.md
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-541
=> Alfredapi 541/installdeps

CHANGELOG.md
https://xenitsupport.jira.com/browse/ALFREDAPI-543
XEP-11 mentions that the `build.gradle` file should also be updated; however, this file is already pointing to version '5.0.1'.
=> [ALFREDAPI-543]: preparation for release 5.0.1

apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/temp/V1SearchWebscriptTest.java
=> ALFREDAPI-547 add validation to for facet size

.github/workflows/ci.yml, .gitignore, CHANGELOG.md, apix-docker/62/build.gradle, apix-docker/70/build.gradle, apix-docker/71/build.gradle, apix-docker/72/build.gradle, apix-docker/73/build.gradle, apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchFacetsServiceImpl.java, apix-impl/src/test/java/eu/xenit/apix/tests/search/SearchFacetServiceUnitTest.java, apix-integrationtests/build.gradle, apix-integrationtests/src/main/java/eu/xenit/apix/rest/v1/tests/temp/V1SearchWebscriptTest.java, apix-integrationtests/src/main/java/eu/xenit/apix/tests/search/SearchServiceFacetsTest.java, apix-integrationtests/src/main/java/eu/xenit/apix/tests/workflow/methods/WorkflowService_SearchContextMyPooledTasks_Test.java, build.gradle, de-swagger-reader/build.gradle
Includes tickets from https://xenitsupport.jira.com/browse/ALFREDAPI-545 (epic)
- Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-546
- Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-547
@WimCrols this PR is the merge of 3 smaller PRs
Includes:
- https://github.com/xenit-eu/alfred-api/pull/203
- https://github.com/xenit-eu/alfred-api/pull/204
- https://github.com/xenit-eu/alfred-api/pull/205
There are 2 main regressions:
- Searching on date range breaks the date facet
- Alfred API does not use the maxFilters configuration to return the pre-configured number of facets, and defaults to 100
=> ALFREDAPI-545 Defects and improvements v4.1.1

CHANGELOG.md, apix-impl/src/main/java/eu/xenit/apix/alfresco/search/SearchFacetsServiceImpl.java, apix-impl/src/test/java/eu/xenit/apix/tests/search/SearchFacetServiceUnitTest.java, build.gradle
=> ALFREDAPI-549 Remove facet if datetime range for 4.x

CHANGELOG.md, apix-impl/src/main/java/eu/xenit/apix/SpringConfiguration.java, build.gradle, src/config/module-context.xml
https://xenitsupport.jira.com/browse/ALFREDAPI-554
Problem: Alfred API's service beans (e.g. ISearchService) are present in a separate child application context, making them unavailable for AMPs to be used.
This PR makes the beans of the `apix-impl` subproject available in the main application context of Alfresco, which Alfresco also uses when initializing beans of AMPs.
**Note to the reviewer:** I noticed that running the `test` Gradle task does not work. The following problems occur:
TypeServiceUnitTest:
- testGetTypeDefinition_returnsNull_whenQnameInvalid
SetMetadataUnitTest:
- testGeneralizeTypeWithCleanUpEnabled
- testGeneralizeTypeWithCleanUpdisabled
SearchFacetServiceUnitTest:
- assertThat_getFacetResults_returnIncludes_translationsForListOfValueConstraints
SearchServiceUnitTest:
- …
=> [ALFREDAPI-554] make service beans available in main application context

.github/workflows/ci.yml, .github/workflows/website-publish.yml, CHANGELOG.md, build.gradle, docs/README.md, docs/build-website.sh, docs/build.gradle, docs/swagger-ui/swagger.json, settings.gradle
This has already been done twice without being committed to the main repository. We should make this a permanent change
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-552
- [N/A] Is error handling done through a method annotated with `@ExceptionHandler` in the webscript classes?
=> ALFREDAPI-552 update swagger spec to be oa2 compliant

CHANGELOG.md, alfred-api-docker/231/docker-compose.yml, alfred-api-docker/232/docker-compose.yml, docs/user/user-guide.md
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-568
=> Alfredapi 568: Set Tomcat casual multipart to true for integration testing

CHANGELOG.md, build.gradle, docs/swagger-ui/swagger.json
Release Alfred API v6.1.0: https://xenitsupport.jira.com/browse/ALFREDAPI-570
=> ALFREDAPI-570 Release Alfred API v6.1.0

.github/workflows/website-publish.yml
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-570
=> ALFREDAPI-570 Upgraded actions/upload-artifact action to v4

README.md
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-571
=> ALFREDAPI-571: Added branching and releasing to README

docs/user/user-guide.md
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-575
=> ALFREDAPI-575: Removed casual multipart paragraph from docs

.github/workflows/ci.yml, CHANGELOG.md
Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-581
=> ALFREDAPI-581: Fix interface publish step conditional being ignored
